version: "3.9"

services:
  services_database:
    image: postgres
    container_name: services_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=services_database
    volumes:
      - pgdata:/data/postgres
  product_service_api:
    build: ./services/product-service
    container_name: product_service_api
    ports:
      - 3002:3002
    volumes:
      - .:/usr/app
    links:
      - services_database
    depends_on:
      - services_database

volumes:
  pgdata:
    driver: local
