
name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Install Dependencies
        run: |
          cd ./services/user-service
          yarn
          cd ../order-service
          pip install -r requirements.txt
      
      - name: Build
        run: |
          cd ./services/user-service
          yarn build
          
      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !services/user-service/node_modules"
          target: "~/app/observability-poc"
          
      - name: Update APIs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/app/observability-poc/services/user-service
            yarn
            cd ~/app/observability-poc/services/order-service
            pip install -r requirements.txt
            pm2 restart user-service-api
            pm2 restart order-service-api

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./services/product-service/
          push: true
          dockerfile: ./Dockerfile
          tags: erickivel/product-service-api:latest
      - name: Set permissions for private key
        run: |
          echo "${{ env.SSH_KEY }}" > key.pem
          chmod 600 key.pem
      - name: Pull Docker image
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem app@${{ secrets.SSH_HOST }} 'sudo docker pull erickivel/product-service-api:latest'
      - name: Rebuild container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem app@${{ secrets.SSH_HOST }} 'sudo docker-compose up --build -d || true'
